### ISSUE TITLE
What's this Engine plugin for?

### ISSUE THREAD

**Issue by hedecai** [retejs/engine#1]
Hi.

Is this plugin try to implement FOR and IF flow control?

**Comment by Ni55aN** [comment]
yes, using [ControlFlow](https://github.com/retejs/engine/blob/43d0dbc649e0431d59a0fd650d400d2be9383099/src/control-flow.ts#L11).
But.. this is a plugin for the future v2 of Rete.js

**Comment by hedecai** [comment]
When will you plan to release the v2 version of Rete.js?

**Comment by Ni55aN** [comment]
beta version will be available within a month
